// Generated by ginue
module.exports = {
  appId: '176',
  code: '',
  name: '顧客管理',
  description:
    '<div>顧客名、担当者名、連絡先などお客様の情報を登録するアプリです。</div>    <div>また、このアプリの会社名と合致する「案件情報」アプリのレコード一覧を表示することができるので、</div><div>あるお客様の顧客情報と、その案件を1画面でまとめて確認できます。</div><div><br /></div><div><div>本アプリは「案件管理」「活動履歴」と同じく、営業支援パックの構成アプリの一つです。</div><div>営業支援パックの詳細説明は<a href="https://jp.cybozu.help/ja/k/user/sales_pack.html">こちらのヘルプページ</a>をご参照ください。</div></div>',
  createdAt: '2021-08-11T08:36:56.000Z',
  creator: {
    code: 'akaza',
    name: 'akaza',
  },
  modifiedAt: '2021-08-11T08:36:56.000Z',
  modifier: {
    code: 'akaza',
    name: 'akaza',
  },
  spaceId: '36',
  threadId: '36',
}
