// Generated by ginue
module.exports = {
  reports: {
    '見込み金額（確度別）': {
      id: '2063',
      chartType: 'COLUMN',
      chartMode: 'NORMAL',
      name: '見込み金額（確度別）',
      index: '0',
      groups: [
        {
          code: '確度',
        },
      ],
      aggregations: [
        {
          type: 'SUM',
          code: 'プラン費用',
        },
      ],
      filterCond: '',
      sorts: [
        {
          by: 'TOTAL',
          order: 'DESC',
        },
      ],
      periodicReport: null,
    },
  },
}
