// Generated by ginue
module.exports = {
  reports: {
    月別活動量推移: {
      id: '5520204',
      chartType: 'LINE',
      name: '月別活動量推移',
      index: '0',
      groups: [
        {
          code: '対応日時',
          per: 'MONTH',
        },
      ],
      aggregations: [
        {
          type: 'COUNT',
        },
      ],
      filterCond: '',
      sorts: [
        {
          by: 'GROUP1',
          order: 'ASC',
        },
      ],
      periodicReport: null,
    },
    対応内容別活動比率: {
      id: '5520206',
      chartType: 'PIE',
      name: '対応内容別活動比率',
      index: '1',
      groups: [
        {
          code: '対応内容',
        },
      ],
      aggregations: [
        {
          type: 'COUNT',
        },
      ],
      filterCond: '',
      sorts: [
        {
          by: 'GROUP1',
          order: 'ASC',
        },
      ],
      periodicReport: null,
    },
  },
}
