// Generated by ginue
module.exports = {
  name: '活動履歴-dev',
  description:
    '<div>顧客、案件に紐付けて活動の履歴を残すことができるアプリです。<br /></div><div><div>顧客管理、および案件管理アプリから情報をルックアップして関連付けることができます。</div></div><div><br /></div><div>本アプリは「顧客管理」「案件管理」と同じく、営業支援パックの構成アプリの一つです。</div><div>営業支援パックの詳細説明は<a href="https://jp.cybozu.help/ja/k/user/sales_pack.html">こちらのヘルプページ</a>をご参照ください。</div>',
  icon: {
    type: 'FILE',
    file: {
      fileKey: '202108110811249D6321E5465545D6AD4F66E5CED52DC9235',
      name: '議事録管理.png',
      contentType: 'image/png',
      size: '4154',
    },
  },
  theme: 'WHITE',
}
